export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST="MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS="MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL="MY_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";




export const ALL_ORDERS_REQUEST_ADMIN="ALL_ORDERS_REQUEST_ADMIN";
export const ALL_ORDERS_SUCCESS_ADMIN="ALL_ORDERS_SUCCESS_ADMIN";
export const ALL_ORDERS_FAIL_ADMIN="ALL_ORDERS_FAIL_ADMIN";

export const DELETE_ORDER_REQUEST_ADMIN="DELETE_ORDER_REQUEST_ADMIN";
export const DELETE_ORDER_SUCCESS_ADMIN="DELETE_ORDER_SUCCESS_ADMIN";
export const DELETE_ORDER_RESET_ADMIN="DELETE_ORDER_RESET_ADMIN";
export const DELETE_ORDER_FAIL_ADMIN="DELETE_ORDER_FAIL_ADMIN";

export const UPDATE_ORDER_REQUEST_ADMIN="UPDATE_ORDER_REQUEST_ADMIN";
export const UPDATE_ORDER_SUCCESS_ADMIN="UPDATE_ORDER_SUCCESS_ADMIN";
export const UPDATE_ORDER_RESET_ADMIN="UPDATE_ORDER_RESET_ADMIN";
export const UPDATE_ORDER_FAIL_ADMIN="UPDATE_ORDER_FAIL_ADMIN";






export const CLEAR_ERRORS="CLEAR_ERRORS";