export const ALL_PRODUCTS_REQUEST="ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL="ALL_PRODUCTS_FAIL";

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST="NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS="NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET="NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL="NEW_REVIEW_FAIL";













export const ALL_PRODUCTS_REQUEST_ADMIN="ALL_PRODUCTS_REQUEST_ADMIN";
export const ALL_PRODUCTS_SUCCESS_ADMIN="ALL_PRODUCTS_SUCCESS_ADMIN";
export const ALL_PRODUCTS_FAIL_ADMIN="ALL_PRODUCTS_FAIL_ADMIN";

export const CREATE_PRODUCT_REQUEST_ADMIN="CREATE_PRODUCT_REQUEST_ADMIN";
export const CREATE_PRODUCT_SUCCESS_ADMIN="CREATE_PRODUCT_SUCCESS_ADMIN";
export const CREATE_PRODUCT_RESET_ADMIN="CREATE_PRODUCT_RESET_ADMIN";
export const CREATE_PRODUCT_FAIL_ADMIN="CREATE_PRODUCT_FAIL_ADMIN";

export const DELETE_PRODUCT_REQUEST_ADMIN="DELETE_PRODUCT_REQUEST_ADMIN";
export const DELETE_PRODUCT_SUCCESS_ADMIN="DELETE_PRODUCT_SUCCESS_ADMIN";
export const DELETE_PRODUCT_RESET_ADMIN="DELETE_PRODUCT_RESET_ADMIN";
export const DELETE_PRODUCT_FAIL_ADMIN="DELETE_PRODUCT_FAIL_ADMIN";

export const UPDATE_PRODUCT_REQUEST_ADMIN="UPDATE_PRODUCT_REQUEST_ADMIN";
export const UPDATE_PRODUCT_SUCCESS_ADMIN="UPDATE_PRODUCT_SUCCESS_ADMIN";
export const UPDATE_PRODUCT_RESET_ADMIN="UPDATE_PRODUCT_RESET_ADMIN";
export const UPDATE_PRODUCT_FAIL_ADMIN="UPDATE_PRODUCT_FAIL_ADMIN";






export const CLEAR_ALL_ERRORS="CLEAR_ALL_ERRORS";
